name: Deploy GitHub Pages with GUI Bootstrap

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run full Pages GUI bootstrap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: bash scripts/bootstrap_full_pages_gui.sh

      - name: Commit regenerated GUI & roles
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/_data/navigation.yml docs/_data/roles.yml docs/_data/permissions.yml docs/index.md docs/admin/index.md
          git commit -m "chore: regenerate GUI + admin + roles [skip ci]" || echo "No changes"

      - name: Push regeneration
        run: git push

      - uses: actions/configure-pages@v5

      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
